apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumigator.fullname" . }}-backend
  labels:
    {{- include "lumigator.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- . | toYaml | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "lumigator.labels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lumigator.fullname" . }}-frontend
  labels:
    {{- include "lumigator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "lumigator.labels" . | nindent 4 }}
