{{ include "lumigator.mistral-default-secret" . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lumigator.fullname" . }}-backend
  labels:
    {{- include "lumigator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.replicaCount }}
  selector:
    matchLabels:
      {{- include "lumigator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lumigator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ .Values.backend.serviceAccountName }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{- include "lumigator.backend.image.repository" . }}:{{- include "lumigator.backend.tag" . }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.backend.service.port }}
              protocol: TCP
          env:
            - name: AWS_ACCESS_KEY_ID
              value: {{ .Values.backend.AWSAccessKey | quote }}
            - name: AWS_SECRET_ACCESS_KEY
              value: {{ .Values.backend.AWSSecretKey | quote }}
            - name: S3_ENDPOINT_URL
              value: {{ .Values.backend.s3EndpointURL | quote }}
            - name: AWS_ENDPOINT_URL
              value: {{ .Values.backend.AWSEndpointURL | quote }}
            - name: S3_BUCKET
              value: {{ required "Missing S3 bucket name" .Values.backend.s3Bucket | quote }}
            - name: POSTGRES_DB
              value: {{ required "Missing PostgreSQL database name" .Values.backend.postgresDb | quote }}
            - name: POSTGRES_HOST
              value: {{ required "Missing PostgreSQL hostname" .Values.backend.postgresHost | quote }}
            - name: POSTGRES_PORT
              value: {{ required "Missing PostgreSQL port" .Values.backend.postgresPort | quote }}
            - name: POSTGRES_USER
              value: {{ required "Missing PostgreSQL user" .Values.backend.postgresUser | quote }}
            - name: POSTGRES_PASSWORD
              value: {{ required "Missing PostgreSQL password" .Values.backend.postgresPassword | quote }}
            - name: RAY_HEAD_NODE_HOST
              value: {{ required "Missing Ray head node hostname" .Values.backend.rayAddress | quote }}
            - name: RAY_DASHBOARD_PORT
              value: {{ required "Missing Ray dashboard node port" .Values.backend.rayPort | quote }}
            - name: RAY_WORKER_GPUS
              value: {{ required "Missing Ray Worker GPU number" .Values.backend.rayWorkerGPUs | quote }}
              # pragma: allowlist-nextline secret
            {{- if or .Values.backend.mistralAPIKey .Values.backend.existingMistralAPISecret }}
            - name: MISTRAL_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "lumigator.mistral-secret-ref" . }}
                  key: {{ .Consts.mistralSecretKey }}
            {{- end }}
            {{- if or .Values.backend.openaiAPIKey .Values.backend.existingOpenaiAPISecret }}
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "lumigator.openai-secret-ref" . }}
                  key: {{ .Consts.openaiSecretKey }}
            {{- end }}
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
